/*抽取mobile_gis中8.16（周四）和8.19（周日）的记录分别存在*/
create table mobile_gis_0820 as select ttime,tmsec,imsi,packets,web_volume,logt,latt from mobile_gis where ttime like '2012-08-20%' order by unix_timestamp(ttime);
/*把经纬度信息转化成double类型，便于比较*/
insert overwrite table mobile_gis_0820 select ttime,tmsec,imsi,packets,web_volume,cast(logt as double) as logt,cast(latt as double) as latt from mobile_gis_0820;
alter table mobile_gis_0820 change column logt logt double; 
/*对一个区块下的每个子区块，以半小时为时间粒度进行统计。包括三类统计：总用户数，总包数，总流量*/
select count(distinct imsi),sum(packets),sum(web_volume) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 10:00:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 10:30:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';

hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 01:00:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 01:30:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 01:30:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 02:00:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 02:00:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 02:30:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 02:30:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 03:00:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 03:00:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 03:30:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 03:30:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 04:00:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 04:00:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 04:30:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 04:30:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 05:00:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 05:00:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 05:30:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst



hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 05:30:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 06:00:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 06:00:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 06:30:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 06:30:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 07:00:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 07:00:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 07:30:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 07:30:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 08:00:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 08:00:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 08:30:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 08:30:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 09:00:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 09:00:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 09:30:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 09:30:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 10:00:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 10:00:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 10:30:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 10:30:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 11:00:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 11:00:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 11:30:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 11:30:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 12:00:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 12:00:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 12:30:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 12:30:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 13:00:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 13:30:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 14:00:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 14:00:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 14:30:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 14:30:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 15:00:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 15:00:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 15:30:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 15:30:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 16:00:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 16:00:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 16:30:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 16:30:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 17:00:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 17:00:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 17:30:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 17:30:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 18:00:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 18:00:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 18:30:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 18:30:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 19:00:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 19:00:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 19:30:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 19:30:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 20:00:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 20:00:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 20:30:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 20:30:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 21:00:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 21:00:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 21:30:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 21:30:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 22:00:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 22:00:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 22:30:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 22:30:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 23:00:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 23:00:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 23:30:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst
hive -e "select count(distinct imsi),sum(packets),sum(web_volume),count(distinct logt,latt) from mobile_gis_0820 where unix_timestamp(ttime) >= unix_timestamp('2012-08-20 23:30:00') and unix_timestamp(ttime) < unix_timestamp('2012-08-20 24:00:00') and logt > '${location[0]}' and  logt < '${location[1]}' and latt > '${location[2]}' and latt < '${location[3]}';" >> /home/wanghaiyang/worspace/respiratory/0820/15/data/${cell}.rst


